
<%

Dim rsCount
Dim objConn
Dim objRec
Dim sql

strFirstName = Request.Form("First_Name")
strLastName = Request.Form("Last_Name")
strExtention = Request.Form("Extention")
strPassword = Request.Form("Password")
strDepartment = Request.Form("Department")
strCountry = Request.Form("Country")
Set objConn = Server.CreateObject ("ADODB.Connection")
Set objRec = Server.CreateObject ("ADODB.Recordset")
strEmail=Request.Form("Logon_Name")
strUserAdded=Request.Form("UserAdded")
Set objConn=Server.CreateObject("ADODB.Connection")
objConn.Open "DSN=Helpdesk2"

Set objREC=objConn.Execute("Select * from UserInfo")
Set rsCount=objConn.Execute("SELECT Count(*) from UserInfo WHERE Email = ('" & strEmail & "')")

If rsCount(0) > 0 then
Response.Write "This E-mail already exists in our database.  If you think this is incorrect, please contact the IT Help Desk. If you have forgotten your password, click <a href=login.asp>here</a>."

objRec.close
objConn.Close
Set objRec = Nothing
Set objConn = Nothing

Else
objRec.close
objRec.Open "UserInfo", objConn

sql = "INSERT INTO UserInfo(FirstName, LastName, Extention, Email, Password, Department, Country,UserAdded) VALUES('"& strFirstName & "','"& strLastName & "','"&strExtention & "', '"&strEmail & "', '"& strPassword & "', '"& strDepartment & "', '"& strCountry & "','" & strUserAdded & "');"
		
objConn.Execute(sql)

objRec.close
objConn.Close
Set objRec = Nothing
Set objConn = Nothing
If strUserAdded = "0" then
	Response.Redirect ("Login.asp")
else
Set objConn=Server.CreateObject("ADODB.Connection")
	objConn.Open "DSN=Helpdesk2"
	Set objRs2=objConn.Execute("Select * from Domains WHERE Country = '"& strCountry &"'")
	stremail =stremail & objRs2("Domain")
Set objCDOMail = Server.CreateObject("CDONTS.NewMail")
	' Set the properties of the object
	objCDOMail.From = "support@purefishing.com" 
	objCDOMail.To = stremail ' + "; bsweyant@purefishing.com"
	objCDOMail.Subject = "Welcome to the Online Help Desk"
	objCDOMail.Body =  strFirstName + "," + vbcrlf + "An Online Help Desk account has been created for you by " + Session("FirstName") + " " + Session("LastName") + ".  You can now login to the Online Help Desk at the following address: http://172.16.3.10/." + vbcrlf + vbcrlf + "Your username and password are as follows:" + vbcrlf + "Username: " + strEmail + vbcrlf + "Password: "+ strPassword + vbcrlf + vbcrlf + "Once you are logged in, you can view the status of, update, or close any open tickets you might have.  You can also look back through all your old tickets, or open a new ticket.  Please be sure to read the help information if you have any questions, or contact your local IT Help Desk for further information." + vbcrlf + vbcrlf + "*******************************************************" + vbcrlf + vbcrlf + "This message has been auto-generated by the Online Help Desk.  Please do not reply to this message."
	objCDOMail.Send

Set objCDOMail = Nothing   
	Response.Redirect ("UserWindow.asp")
end If	
End if 

%>