<%

Dim objConn
Dim objRec
Dim objRs
Dim sql
Dim sql2
Dim SolutionDesc
Dim strDate
Dim DTStamp

Set objConn = Server.CreateObject ("ADODB.Connection")
Set objRec = Server.CreateObject ("ADODB.Recordset")
strSendEmail=Request.form("SendeMail")
strEmail=Request.form("Email")
strCC_Mail=Request.form("CC_Mail")	
strUFName=Request.form("UFName")	
strULName=Request.form("ULName")	
objConn.Open "DSN=HelpDesk2"
objRec.Open "Calls", objConn

ProblemDesc = Replace(Request.form("Problem_Desc"), "'", "''")
SolutionDesc = Replace(Request.form("Solution_Desc"), "'", "''")
ROI = Replace(Request.form("ROI"), "'", "''")
Problem = Request.form("Problem_Desc")
SolutionDesc = SolutionDesc + vbcrlf  + "---------------------" +  Session("FirstName") + " " + Session("LastName") + " - " + CStr(now) + vbcrlf + vbcrlf
'Solution = SolutionDesc

If Request.Form("Projected_Complete_Date") = "" then
	strProjected_Complete_Date= Request.Form("Projected_Complete_Date2")
Else
	strProjected_Complete_Date= Request.Form("Projected_Complete_Date")
end if

If Request.Form("Date_Closed") = "" then
	strDate= Request.Form("Date_Closed2")
Else
	strDate= Request.Form("Date_Closed")
end if
If Request.Form("Time_Closed") = "" then
	strTime= Request.Form("Time_Closed2")
Else
	strTime= Request.Form("Time_Closed")
end if
sql = "UPDATE Calls SET  Call_Type= '" & Request.Form("Call_Type") & "',Problem_Desc= '" & ProblemDesc & "', Package_Name= '" & Request.Form("Package_Name") & "',  Call_Serviced_By= '" & Request.Form("Call_Serviced_By") & "', Solution_Desc= '" & SolutionDesc & "', Closed= '" & Request.Form("Closed") & "', In_Process= '" & Request.Form("In_Process") & "', Date_Closed= '" & strDate & "', Time_Closed= '" & strTime & "', Priority= '" & Request.Form("Priority") & "', SAPPriority= '" & Request.Form("tickpriority") & "', Upgrade= '" & Request.Form("upgrade") & "', ROI= '" & ROI & "', SAP_Module= '" & Request.Form("SAP_Module") & "',TransportDate='"& Request.Form("TransportDate") &"', Projected_Complete_Date= '" & strProjected_Complete_Date & "' WHERE Ticket_Number=" & Request("Num") & ";"

objConn.Execute(sql)
	
objRec.close
objConn.Close
Set objRec = Nothing
Set objConn = Nothing
TicketNum=Request("Num") 
	
If strSendEmail ="on" Then
	Set objConn=Server.CreateObject("ADODB.Connection")
	objConn.Open "DSN=Helpdesk2"
	Set objRs=objConn.Execute("Select * from UserInfo WHERE WorkerID = '"& Request.Form("Call_Serviced_By") &"'")
	Country=objRs("country")
	fromEmail = objRs("Email")
	objRs.close
	Set objRs = Nothing
	' Set the properties of the object
	Set objRec=objConn.Execute("Select * from Domains WHERE Country = '" & Country & "'")
	strDomain = objRec("Domain")
	objRec.close
	objConn.Close
	Set objRec = Nothing
	Set objConn = Nothing
	
	Set objCDOMail = Server.CreateObject("CDONTS.NewMail")
	objCDOMail.From = fromEmail & strDomain
	objCDOMail.To = stremail
	objCDOMail.CC = strCC_Mail
	objCDOMail.Subject = "Ticket #" + TicketNum
	IF Request.Form("Closed")="Yes" Then
		If Request.Form("Call_Type")="HELP" Then 
			If Request.Form("Call_Serviced_By")="RV" or Request.Form("Call_Serviced_By")="CB" or Request.Form("Call_Serviced_By")="JL" or Request.Form("Call_Serviced_By")="NS" or Request.Form("Call_Serviced_By")="CH" Then
				objCDOMail.Body = "We'd like to hear about your experience with the Help Desk.  Please fill out our survey at: http://172.16.3.10/survey.asp?Num=" + TicketNum + vbcrlf + vbcrlf + "This message has been auto-generated by the Online Help Desk.  Please do not reply to this message.  To provide additional information about your open ticket, please login and update your ticket online at the address below." + vbcrlf + vbcrlf + "**************************************************" + vbcrlf + vbcrlf + strUFName + "," + vbcrlf + vbcrlf +"Ticket #"+ TicketNum + " has been closed." + vbcrlf + "Problem: " + Problem + vbcrlf + vbcrlf + "Solution: " + SolutionDesc + vbcrlf + vbcrlf + "For more details on  this ticket, please visit the following address: http://172.16.3.10/viewticket.asp?Num=" + TicketNum 
			Else
				objCDOMail.Body = "This message has been auto-generated by the Online Help Desk.  Please do not reply to this message.  To provide additional information about your open ticket, please login and update your ticket online at the address below." + vbcrlf + vbcrlf + "**************************************************" + vbcrlf + vbcrlf + strUFName + "," + vbcrlf + vbcrlf +"Ticket #"+ TicketNum + " has been closed." + vbcrlf + "Problem: " + Problem + vbcrlf + vbcrlf + "Solution: " + SolutionDesc + vbcrlf + vbcrlf + "For more details on  this ticket, please visit the following address: http://172.16.3.10/viewticket.asp?Num=" + TicketNum 	
			End If
		Else
			objCDOMail.Body = "This message has been auto-generated by the Online Help Desk.  Please do not reply to this message.  To provide additional information about your open ticket, please login and update your ticket online at the address below." + vbcrlf + vbcrlf + "**************************************************" + vbcrlf + vbcrlf + strUFName + "," + vbcrlf + vbcrlf +"Ticket #"+ TicketNum + " has been closed." + vbcrlf + "Problem: " + Problem + vbcrlf + vbcrlf + "Solution: " + SolutionDesc + vbcrlf + vbcrlf + "For more details on  this ticket, please visit the following address: http://172.16.3.10/viewticket.asp?Num=" + TicketNum  
		End If
	Else
		objCDOMail.Body = "This message has been auto-generated by the Online Help Desk.  Please do not reply to this message.  To provide additional information about your open ticket, please login and update your ticket online at the address below." + vbcrlf + vbcrlf + "**************************************************" + vbcrlf + vbcrlf + strUFName + "," + vbcrlf + vbcrlf +"Ticket #"+ TicketNum + " has been updated." + vbcrlf + "Problem: " + Problem + vbcrlf + vbcrlf + "Solution: " + SolutionDesc + vbcrlf + vbcrlf + "You can see updates to this ticket at any time at the following address: http://172.16.3.10/viewticket.asp?Num=" + TicketNum
	End If
objCDOMail.Send

Set objCDOMail = Nothing    

End if


IF Request.Form("strWorker") <> Request.Form("Call_Serviced_By") and Session("WorkID") <> Request.Form("Call_Serviced_By") then

	Set objConn=Server.CreateObject("ADODB.Connection")
	objConn.Open "DSN=Helpdesk2"
	Set objRs=objConn.Execute("Select * from UserInfo WHERE WorkerID = '"& Request.Form("Call_Serviced_By") &"'")
	Set objRs2=objConn.Execute("Select * from Domains WHERE Country = '"& objRs("Country") &"'")
	Set objRs3=objConn.Execute("Select * from Domains WHERE Country = '"& Session("Country") &"'")
	strSend =objRs("Email") & objRs2("Domain")
	strFromEmail = Session("Email") & objRs3("Domain")
	'strBody="A Help Desk ticket has been assigned to you by " + Session("FirstName") + " " + Session("LastName") + "." + vbCRLF + "Ticket number (if available): " + TicketNum + vbcrlf + vbcrlf + "You can see this ticket at the following address: http://172.16.3.10/modifyticket.asp?Num=" + TicketNum + vbcrlf
	
	strBody="Help Desk ticket #" + TicketNum + " has been assigned to you by " + Session("FirstName") + " " + Session("LastName") + "." + vbcrlf + vbcrlf +"User: " + strUFName + " " + strULName + vbcrlf + vbcrlf + "Problem Description: " + ProblemDesc + vbcrlf + "You can update this ticket at: http://172.16.3.10/modifyticket.asp?Num=" + TicketNum + "."
	objRs.close
	objRs2.close
	objRs3.close
	objConn.Close
	Set objRs = Nothing
	Set objConn = Nothing
	Set objCDOMail = Server.CreateObject("CDONTS.NewMail")
    
	' Set the properties of the object
	objCDOMail.From = strFromEmail '"support@purefishing.com"
	objCDOMail.To = strSend
	objCDOMail.Subject = "You Have a New Ticket"
	objCDOMail.Body = strBody

	objCDOMail.Send

	Set objCDOMail = Nothing  	

End if
If Session("PageName") = "Search"	Then
	Response.Redirect "Search.asp"
Else	
	Response.Redirect "Main.asp"
End IF	
%>

