<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Alantic Rim Help Desk Stats 2004</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="Alantic Rim 2005.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Opened **</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Still Open ***</FONT></TD>
<TD ALIGN="left" Colspan="3"><FONT FACE="MS Sans Serif">Average Close Time for the Month (Help Tickets,Non-Sap)</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">54</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">24</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">30</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">38</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">31 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">111</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">32</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">79</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">72</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">33</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">36 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">101</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">49</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">52</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">68</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">34</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">120</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">54</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">66</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">96</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">32</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">54 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">80</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">25</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">55</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">57</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">21</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">55 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">99</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">32</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">67</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">77</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">54 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">48</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">22</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">34</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">22 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">16 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">99</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">35</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">63</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">74</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">30</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">52 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">78</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">58</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">63</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">27</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">38 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">97</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">31</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">65</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">73</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">27</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">01 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">56 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">73</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">50</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">41</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6 Min</FONT></TD>
</TR>
<tr>
<td Colspan="9">
* Number of Tickets Opened and/or Closed during the month<br>
** For current month<br>
*** Tickets that were opend during the month and were still open at the end of the month<br>
</td>
</tr>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
