<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Alantic Rim Help Desk Stats 2004</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="Alantic Rim 2004.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Opened **</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Still Open ***</FONT></TD>
<TD ALIGN="left" Colspan="3"><FONT FACE="MS Sans Serif">Average Close Time for the Month (Help Tickets,Non-Sap)</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">126</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">76</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">50</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">96</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">51</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">165</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">99</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">66</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">136</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">63</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">111</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">56</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">55</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">74</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">28</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">22 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">58 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">154</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">62</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">92</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">134</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">73</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Hour</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">53 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">93</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">44</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">49</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">59</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">16</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">89</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">57</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">32</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">67</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">71</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">28</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">43</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">45</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">21</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">73</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">32</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">41</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">52</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">57 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">78</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">25</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">53</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">55</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">30</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">46 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">92</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">66</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">58</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">90</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">33</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">57</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">65</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">28</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">56 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">60</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">30</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">30</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">37</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">42 Min</FONT></TD>
</TR>
<tr>
<td Colspan="9">
* Number of Tickets Opened and/or Closed during the month<br>
** For current month<br>
*** Tickets that were opend during the month and were still open at the end of the month<br>

</td>
</tr>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
