<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>North America Help Desk Stats 2004</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="North America 2004.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Opened **</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Still Open ***</FONT></TD>
<TD ALIGN="left" Colspan="3"><FONT FACE="MS Sans Serif">Average Close Time for the Month (Help Tickets,Non-Sap)</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">758</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">405</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">353</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">602</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">192</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">21 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">651</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">328</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">323</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">525</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">130</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">37 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">754</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">386</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">368</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">638</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">106</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">48 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">904</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">516</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">338</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">812</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">170</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">58 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">828</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">395</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">433</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">699</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">124</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">29 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">948</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">413</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">535</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">818</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">123</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">998</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">459</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">539</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">892</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">153</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">43 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">908</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">278</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">630</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">793</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">140</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">07 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">837</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">316</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">521</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">737</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">120</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">882</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">376</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">506</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">728</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">79</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">657</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">258</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">399</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">558</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">98</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">28 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">732</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">226</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">506</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">627</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">85</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">25 Min</FONT></TD>
</TR>
<tr>
<td Colspan="9">
* Number of Tickets Opened and/or Closed during the month<br>
** For current month<br>
*** Tickets that were opend during the month and were still open at the end of the month<br>
</td>
</tr>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
