<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>North America Help Desk Stats 2006</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="North America 2006.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Opened **</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Still Open ***</FONT></TD>
<TD ALIGN="left" Colspan="3"><FONT FACE="MS Sans Serif">Average Close Time for the Month (Help Tickets,Non-Sap)</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">992</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">305</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">651</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">888</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">171</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">35 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">830</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">256</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">548</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">699</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">126</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">31 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD></TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD></TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD></TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD></TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 06</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<tr>
<td Colspan="9">
* Number of Tickets Opened and/or Closed during the month<br>
** For current month<br>
*** Tickets that were opend during the month and were still open at the end of the month<br>
</td>
</tr>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
