<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>North America Help Desk Stats 2004</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="North America 2005.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Opened **</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Still Open ***</FONT></TD>
<TD ALIGN="left" Colspan="3"><FONT FACE="MS Sans Serif">Average Close Time for the Month (Help Tickets,Non-Sap)</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">792</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">270</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">522</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">692</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">112</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">34 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">855</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">261</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">594</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">730</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">141</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">956</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">340</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">616</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">835</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">136</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">968</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">289</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">679</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">849</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">116</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">869</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">295</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">574</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">770</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">122</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">49 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">828</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">295</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">533</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">714</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">97</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">29 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">723</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">225</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">498</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">637</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">130</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">29 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">973</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">346</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">619</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">827</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">130</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">50 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">811</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">272</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">504</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">699</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">127</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">50 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">708</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">240</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">441</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">626</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">110</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">22 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">794</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">187</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">572</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">672</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">97</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">50 Min</FONT></TD>
</TR>
<tr>
<td Colspan="9">
* Number of Tickets Opened and/or Closed during the month<br>
** For current month<br>
*** Tickets that were opend during the month and were still open at the end of the month<br>
</td>
</tr>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
