<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Pacific Rim Help Desk Stats 2004</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="Pacific Rim 2005.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Opened **</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Still Open ***</FONT></TD>
<TD ALIGN="left" Colspan="3"><FONT FACE="MS Sans Serif">Average Close Time for the Month (Help Tickets,Non-Sap)</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">27</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">23 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">25</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">22 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">34</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">20</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">24</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">24</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">16</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">23 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">44 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">20 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">04 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">25</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">23</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">40 Min</FONT></TD>
</TR>
<tr>
<td Colspan="9">
* Number of Tickets Opened and/or Closed during the month<br>
** For current month<br>
*** Tickets that were opend during the month and were still open at the end of the month<br>
</td>
</tr>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
