<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Pacific Rim Help Desk Stats 2004</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="Pacific Rim 2004.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Opened **</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Still Open ***</FONT></TD>
<TD ALIGN="left" Colspan="3"><FONT FACE="MS Sans Serif">Average Close Time for the Month (Help Tickets,Non-Sap)</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">21</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">59 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">20</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">53</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">25</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">28</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">45</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">34 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">49</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">30</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">43</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">28 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">29</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">36</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">31</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">46 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">39</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">27</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">27</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">37 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">31</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">25</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">27 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">6</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">25 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">43 Min</FONT></TD>
</TR>
<tr>
<td Colspan="9">
* Number of Tickets Opened and/or Closed during the month<br>
** For current month<br>
*** Tickets that were opend during the month and were still open at the end of the month<br>
</td>
</tr>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
