<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Help Desk Stats 2004</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="stats2004.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Opened **</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Still Open ***</FONT></TD>
<TD ALIGN="left" Colspan="3"><FONT FACE="MS Sans Serif">Average Close Time for the Month (Help Tickets,Non-Sap)</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">917</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">501</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">416</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">725</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">254</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">46 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">849</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">445</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">404</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">686</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">201</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">36 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">929</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">471</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">458</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">764</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">145</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">43 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1110</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">610</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">500</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">991</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">252</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">962</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">456</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">506</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">795</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">149</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">18 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1078</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">493</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">585</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">918</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">152</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1096</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">493</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">603</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">958</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">186</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">21 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1024</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">323</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">701</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">873</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">173</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">21 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">947</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">354</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">593</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">818</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">115</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">43 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">993</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">411</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">582</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">803</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">108</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">764</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">296</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">468</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">637</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">133</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">54 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 04</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">810</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">263</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">547</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">674</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">105</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">55 Min</FONT></TD>
</TR>
<tr>
<td Colspan="9">
* Number of Tickets Opened and/or Closed during the month<br>
** For current month<br>
*** Tickets that were opend during the month and were still open at the end of the month<br>
</td>
</tr>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
