<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Help Desk Stats 2002</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="stats2002.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">337</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">265</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">72</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">270</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">214</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">56</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">318</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">250</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">68</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">329</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">230</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">99</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">230</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">182</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">48</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">343</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">270</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">73</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">306</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">239</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">67</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">367</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">274</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">93</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">248</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">197</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">51</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">308</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">251</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">57</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">258</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">183</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">75</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">227</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">154</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">73</FONT></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<FONT SIZE=-1><I>
<BR>Last Updated on 12/3/02
<BR>By cdburton
<FONT SIZE=+0></I>
</BODY>
</HTML>
