<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Help Desk Stats 2001</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="stats1.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">232</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">138</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">94</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Febuary 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">226</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">113</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">113</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">83</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">50</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">33</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">83</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">48</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">35</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">76</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">52</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">24</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">50</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">33</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">185</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">127</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">58</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">124</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">90</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">34</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">212</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">175</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">37</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">236</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">157</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">79</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">179</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">150</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">29</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 01</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">165</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">121</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">44</FONT></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<FONT SIZE=-1><I>
<BR>Last Updated on 1/2/02
<BR>By cdburton
<FONT SIZE=+0></I>
</BODY>
</HTML>
