<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Help Desk Stats 2003</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="stats2003.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">333</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">208</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">125</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">320</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">223</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">97</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">339</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">227</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">112</font></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">312</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">223</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">89</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">355</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">248</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">107</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">336</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">224</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">112</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">367</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">245</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">122</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">383</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">261</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">122</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">486</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">321</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">165</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1126</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">917</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">209</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">620</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">460</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">160</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">690</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">413</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">277</FONT></TD>
</TR>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
