<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Help Desk Stats 2005</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="stats2005.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets *</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Opened **</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Tickets Still Open ***</FONT></TD>
<TD ALIGN="left" Colspan="3"><FONT FACE="MS Sans Serif">Average Close Time for the Month (Help Tickets,Non-Sap)</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">875</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">307</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">568</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">757</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">129</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">995</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">310</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">685</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">824</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">183</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1092</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">404</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">688</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">927</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">179</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">37 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1128</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">363</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">765</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">977</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">156</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">46 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">978</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">334</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">644</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">851</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">148</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">950</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">338</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">612</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">807</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">120</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">36 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">787</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">255</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">532</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">684</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">152</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1097</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">395</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">693</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">992</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">164</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">35 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">915</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">298</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">578</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">784</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">156</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Days</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">826</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">280</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">518</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">718</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">141</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">36 Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"></FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif"> Min</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 05</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">902</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">219</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">643</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">745</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">117</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0 Day</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11 Hours</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">55 Min</FONT></TD>
</TR>
<tr>
<td Colspan="9">
* Number of Tickets Opened and/or Closed during the month<br>
** For current month<br>
*** Tickets that were opend during the month and were still open at the end of the month<br>
</td>
</tr>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
