<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Alantic Rim Help Desk Stats 2003</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="SwedenStats2003.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">22</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">17</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">19</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">10</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">9</font></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">25</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">33</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">22</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">11</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">41</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">12</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">29</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">13</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">30</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">14</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">16</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">54</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">30</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">24</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">249</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">207</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">42</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">89</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">63</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">26</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">75</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">43</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">32</FONT></TD>
</TR>
</Table><!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->

</BODY>
</HTML>
