<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>Taiwan Help Desk Stats 2002</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="TaiwanStats2002.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">15</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">8</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">7</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">4</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">1</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">0</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">5</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">3</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">2</FONT></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<FONT SIZE=-1><I>
<BR>Last Updated on 12/3/02
<BR>By cdburton
<FONT SIZE=+0></I>
</BODY>
</HTML>
