<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>US Help Desk Stats 2002</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="USstats2002.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">320</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">252</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">68</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">258</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">205</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">53</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">294</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">234</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">60</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">312</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">219</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">93</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">214</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">174</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">40</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">334</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">265</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">69</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">294</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">229</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">65</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">353</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">263</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">90</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">236</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">288</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">48</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">294</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">242</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">52</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">226</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">170</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">56</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 02</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">204</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">144</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">60</FONT></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<FONT SIZE=-1><I>
<BR>Last Updated on 12/3/02<BR>By cdburton
<FONT SIZE=+0></I>
</BODY>
</HTML>
