<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<TITLE>North America Help Desk Stats 2003</TITLE>
</HEAD>
<BODY>
<!-- The following table was generated by the Internet Assistant Wizard for Microsoft Excel. -->
<!-- ------------------------- -->
<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<P>
<IMG SRC="USstats2003.gif" ALT="Chart Help Desk Stats" ALIGN=CENTER>
</P>
<Table border align="center">
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Month/Year</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Help Tickets</FONT></TD>
<TD ALIGN="left"><FONT FACE="MS Sans Serif">Total Request Tickets</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">January 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">313</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">201</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">112</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">February 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">276</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">195</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">81</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">March 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">281</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">194</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">87</font></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">April 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">244</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">189</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">55</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">May 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">293</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">215</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">78</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">June 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">283</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">209</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">77</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">July 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">317</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">220</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">97</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">August 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">332</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">239</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">93</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">September 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">409</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">285</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">124</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">October 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">822</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">674</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">148</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">November 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">510</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">384</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">126</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="left"><FONT FACE="MS Sans Serif">December 03</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">589</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">355</FONT></TD>
<TD ALIGN="right"><FONT FACE="MS Sans Serif">234</FONT></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
</BODY>
</HTML>
